### ISSUE TITLE
请问怎么创建文件夹？

### ISSUE THREAD

**Issue by ldlywt** [alibaba/aliyunpan-android-sdk#14]
我想在阿里云盘创建文件夹，如果有就不创建，然后把文件上传到文件夹。

**Comment by LiCola-Exist** [comment]
https://www.yuque.com/aliyundrive/zpfszx/ezlzok#Rptze

**Comment by LiCola-Exist** [comment]
参考[文件创建 ](https://www.yuque.com/aliyundrive/zpfszx/ezlzok#Rptze) type=folder @ldlywt

**Comment by ldlywt** [comment]
![image](https://github.com/alibaba/aliyunpan-android-sdk/assets/17981095/1a09eb14-00f3-403c-be62-31a83ad90d5d)
我用的 Android sdk，我看有这个方法，想问下这个parentFileId 怎么传？

**Comment by LiCola-Exist** [comment]
![image](https://github.com/alibaba/aliyunpan-android-sdk/assets/15816280/cf894398-98f7-404e-b3fc-a5dd75f0dc46)
这个方法的话可以不传默认根目录，否则就选拉出[文件列表](https://www.yuque.com/aliyundrive/zpfszx/zqkqp6#DEYA4)再选一个文件夹
