### ISSUE TITLE
每次用阿里云盘客户端授权的时候在客户端显示的是授权结果页

### ISSUE THREAD

**Issue by BenjaminSong90** [alibaba/aliyunpan-android-sdk#18]
sdk版本号：v0.2.1
问题：每次用阿里云盘客户端授权的时候在客户端显示的是授权结果页，如果用H5授权是正常的

**Comment by LiCola-Exist** [comment]
原因是自动授权的兼容性问题，问题已经修复。请使用最新版的v0.2.2
